apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.ServiceName }}
spec:
  selector:
    app: {{ .Values.AppName }}
  ports:
  - protocol: TCP
    port: {{ .Values.ServicePort }}
    targetPort: {{ .Values.ContainerPort }}